spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:mysql://localhost:3306/wannacode
    username: root
    password: flavio2000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 0

eureka:
  instance:
    instance-id:  ${spring.application.name}:${random.uuid}

