product:
  property: product dev

spring:
  application:
    name: product



data:
    mongodb:
      uri: mongodb://localhost:27017/productdb


server:
  port: 0

eureka:
    instance:
      instance-id:  ${spring.application.name}:${random.uuid}


management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

app:
  config: "Cuarta Configuracion escritas despues de la ejecucion"